---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  # - dir_mode=0777
  # - file_mode=0777
  - uid=1
  - gid=1
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS